# ndarray

## 1. characteristics of ndarray

### multi-dimensional


In [1]:
import numpy as np

In [2]:
arr = np.array(5)
print(arr)
print("arr's dimensional: ", arr.ndim)

5
arr's dimensional:  0


In [3]:
arr = np.array([1, 2, 3])
print(arr)
print("arr's dimensional: ", arr.ndim)

[1 2 3]
arr's dimensional:  1


In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print("arr's dimensional: ", arr.ndim)

[[1 2 3]
 [4 5 6]]
arr's dimensional:  2


### homogeneity


In [5]:
arr = np.array([1, "hello"])  # auto force type convertion
print(arr)

['1' 'hello']


In [6]:
arr = np.array([1, 2.5])
print(arr)

[1.  2.5]


## 2. attribute of ndarray


In [7]:
arr = np.array([[1, 2.5, 3], [4, 5, 6]])
print(arr)
print("shape of array: ", arr.shape)
print("dimension of array: ", arr.ndim)
print("number of elements: ", arr.size)
print("data type of elements: ", arr.dtype)
print("transpose elements: ", arr.T)

[[1.  2.5 3. ]
 [4.  5.  6. ]]
shape of array:  (2, 3)
dimension of array:  2
number of elements:  6
data type of elements:  float64
transpose elements:  [[1.  4. ]
 [2.5 5. ]
 [3.  6. ]]


## 3. creation of ndarray


In [8]:
arr = np.array([1, 2, 3], dtype=np.float64)
print(arr.ndim)
print(arr)

1
[1. 2. 3.]


In [9]:
arr1 = np.copy(arr)
print(arr1)
arr1[0] = 8
print(arr1)
print(arr)

[1. 2. 3.]
[8. 2. 3.]
[1. 2. 3.]


In [10]:
arr = np.zeros((2, 3), dtype=int)
print(arr)
print(arr.dtype)

[[0 0 0]
 [0 0 0]]
int64


In [11]:
arr = np.zeros((2,), dtype=int)
print(arr)

[0 0]


In [12]:
arr = np.ones((5, 8), dtype=int)
print(arr)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [13]:
arr = np.empty((4, 5))
print(arr)

[[1.33397724e-322 0.00000000e+000 4.24566530e-058 3.10503618e+231
  4.94694589e-313]
 [0.00000000e+000 9.94646473e+086 3.89590524e-319 4.93275141e-320
  1.84734147e+106]
 [9.49111963e-318 0.00000000e+000 1.66590868e+135 5.92878775e-323
  7.13351742e-319]
 [3.25925330e-313 3.20752203e+111 4.67512562e-314 4.22199099e-308
  1.83479889e+106]]


In [14]:
arr = np.full((3, 4), 2025)
print(arr)

[[2025 2025 2025 2025]
 [2025 2025 2025 2025]
 [2025 2025 2025 2025]]


In [15]:
arr1 = np.zeros_like(arr)
print(arr1)
arr1 = np.empty_like(arr)
print(arr1)
arr1 = np.ones_like(arr)
print(arr1)
arr1 = np.full_like(arr, 2026)
print(arr1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[      2130299885480                  64                   0
                    0]
 [  19140693553315840 3546639901990925923 7293359939923424310
  3761694476598654520]
 [4135542723730158647 7004897760863466852 4049358634292896614
  7004615173457065060]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[2026 2026 2026 2026]
 [2026 2026 2026 2026]
 [2026 2026 2026 2026]]


In [16]:
arr = np.arange(2, 10, 2)
print(arr)

[2 4 6 8]


In [17]:
arr = np.linspace(0, 10, 5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [18]:
arr = np.linspace(0, 100, 5, dtype=int)
print(arr)

[  0  25  50  75 100]


In [19]:
arr = np.logspace(0, 4, 3, base=2)
print(arr)

[ 1.  4. 16.]


In [20]:
# arr = np.eye(3)
arr = np.eye(3, 4, dtype=int)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [21]:
arr = np.diag([1, 2, 3])
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [22]:
arr = np.random.rand(2, 3)
print(arr)

[[0.74391473 0.39067951 0.14623784]
 [0.34785816 0.62857529 0.40377525]]


In [23]:
arr = np.random.uniform(3, 6, (2, 3))
print(arr)

[[5.8054118  3.66759893 4.56793472]
 [4.80644943 3.37841916 3.91423194]]


In [24]:
arr = np.random.randint(3, 30, (2, 3))
print(arr)

[[ 7 18  3]
 [25  8  4]]


In [25]:
arr = np.random.randn(2, 3)  # -3 ~ 3
print(arr)

[[-0.4915452   1.25477012 -0.436135  ]
 [ 0.7864684  -1.29493574 -1.04676929]]


In [26]:
np.random.seed(20)
arr = np.random.randint(1, 10, (2, 5))
print(arr)

[[4 5 7 8 3]
 [1 7 9 6 4]]


### 4. data type of ndarray

bool

int uint

float

complex


In [27]:
# arr = np.array([1, 0, 2, 0], dtype = np.bool)
arr = np.array([1, 0, 2000, 0], dtype=np.int64)
print(arr)

[   1    0 2000    0]


### 5. index and slice


In [28]:
arr = np.random.randint(1, 100, 20)
print(arr)

[17 63 17  8 99  7 27 14 76 59 26  4 75 76 62 78 84 58 95 33]


In [29]:
print(arr[0])
print(arr[:])
print(arr[2:5])  # start:end+1
print(arr[slice(2, 15, 3)])  # (start, end, step)
print(arr[(arr > 10) & (arr < 70)])  # bool index

17
[17 63 17  8 99  7 27 14 76 59 26  4 75 76 62 78 84 58 95 33]
[17  8 99]
[17  7 76  4 62]
[17 63 17 27 14 59 26 62 58 33]


In [30]:
arr = np.random.randint(1, 100, (4, 8))
print(arr)

[[11  7 76 19  4 78 18 44]
 [17 19 80 91 60 72 76 30]
 [46  7 64 79 25 19 94 34]
 [79 43 95  4 19 71 53 23]]


In [31]:
print(arr[1, 3])
print(arr[1, 2:5])
print(arr[2][arr[2] > 50])

91
[80 91 60]
[64 79 94]


### 5. operation of ndarray


In [32]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a**2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [33]:
c = [1, 2, 3]
d = [4, 5, 6]
for i in range(len(c)):
    d[i] += c[i]
print(d)

[5, 7, 9]


In [34]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[4, 5, 6], [7, 8, 9], [1, 2, 3]])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a**2)

[[ 5  7  9]
 [11 13 15]
 [ 8 10 12]]
[[-3 -3 -3]
 [-3 -3 -3]
 [ 6  6  6]]
[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]
[[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]
 [7.         4.         3.        ]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [35]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a + 3)
print(a * 3)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [36]:
# broadcast
a = np.array([1, 2, 3])
b = np.array([[4], [5], [6]])
print(a + b)
print(b - a)

[[5 6 7]
 [6 7 8]
 [7 8 9]]
[[3 2 1]
 [4 3 2]
 [5 4 3]]


In [37]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[4, 5, 6], [7, 8, 9], [1, 2, 3]])
print(a @ b)

[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]


# 2.3 Common functions in numpy

### 1. basic math functions


In [38]:
print(np.sqrt(9))
print(np.sqrt([1, 4, 9]))
arr = np.array([1, 25, 81])
print(np.sqrt(arr))

3.0
[1. 2. 3.]
[1. 5. 9.]


In [39]:
print(np.exp(1))  # e^x

2.718281828459045


In [40]:
print(np.log(2.71))  # lnX

0.9969486348916096


In [41]:
print(np.sin(np.pi / 2))
print(np.cos(np.pi))

1.0
-1.0


In [42]:
arr = np.array([-1, 1, 2, -3])
print(np.abs(arr))

[1 1 2 3]


In [43]:
print(np.power(arr, 3))

[ -1   1   8 -27]


In [44]:
print(np.round([3.2, 4.5, 8.1, 9.6]))

[ 3.  4.  8. 10.]


In [45]:
arr = np.array([1.6, 25.1, 81.7])
print(np.ceil(arr))
print(np.floor(arr))

[ 2. 26. 82.]
[ 1. 25. 81.]


In [46]:
np.isnan([1, 2, np.nan, 3])

array([False, False,  True, False])

### 2. statistical functions


In [47]:
arr = np.random.randint(1, 20, 8)
print(arr)

[15  5 12  9  7 16 19 15]


In [48]:
print(np.sum(arr))

98


In [49]:
print(np.mean(arr))

12.25


In [50]:
print(np.median(arr))
print(np.median([4, 1, 2]))
print(np.median([1, 2, 5, 80]))

13.5
2.0
3.5


In [51]:
print(np.var([1, 2, 3]))
print(np.std([1, 2, 3]))
print(np.var(arr))
print(np.std(arr))

0.6666666666666666
0.816496580927726
20.6875
4.548351349665063


In [52]:
print(arr)
print(np.max(arr), np.argmax(arr))
print(np.min(arr), np.argmin(arr))

[15  5 12  9  7 16 19 15]
19 6
5 1


In [53]:
np.random.seed(0)
arr = np.random.randint(0, 100, 4)
print(arr)
print(np.median(arr))

print(np.percentile(arr, 50))
print(np.percentile(arr, 25))  # 0.25 * 3 * (47 - 44) + 44
print(np.percentile(arr, 0))
print(np.percentile(arr, 100))

[44 47 64 67]
55.5
55.5
46.25
44.0
67.0


In [54]:
arr = np.array([1, 2, 3])
print(np.cumsum(arr))
print(np.cumprod(arr))

[1 3 6]
[1 2 6]


## comparison functions

In [59]:
print(np.greater([3, 4, 5, 6, 7], 4))
print(np.less([3, 4, 5, 6, 7], 4))
print(np.equal([3, 4, 5, 6, 7], 4))
print(np.equal([3, 4, 5], [4, 4, 4]))

[False False  True  True  True]
[ True False False False False]
[False  True False False False]
[False  True False]


In [65]:
print(np.logical_and([1, 0], [1, 1]))
print(np.logical_or([0, 0], [1, 0]))
print(np.logical_not([1, 0]))

[ True False]
[ True False]
[False  True]


In [ ]:
print(np.any([0, 0, 0, 0, 0, 0]))
print(np.all([1, 1, 0, 0, 0, 0]))
print(np.all([1, 1]))

False
False
True


In [71]:
arr = np.array([1, 2, 3, 4, 5])
print(np.where(arr > 3, arr, 0))

[0 0 0 4 5]


In [75]:
score = np.random.randint(50, 100, 20)
print(score)

[59 82 81 60 73 85 61 78 84 50 50 86 55 88 90 67 65 54 91 92]


In [ ]:
print(np.where(score < 60, "bad", np.where(score < 80, "good", "great")))

['bad' 'great' 'great' 'good' 'good' 'great' 'good' 'good' 'great' 'bad'
 'bad' 'great' 'bad' 'great' 'great' 'good' 'good' 'bad' 'great' 'great']


In [80]:
print(
    np.select(
        [score > 80, (score >= 60) & (score <= 80), score < 60],
        ["great", "good", "bad"],
        default="unknown",
    )
)

['bad' 'great' 'great' 'good' 'good' 'great' 'good' 'good' 'great' 'bad'
 'bad' 'great' 'bad' 'great' 'great' 'good' 'good' 'bad' 'great' 'great']


In [86]:
# sorting functions
np.random.seed(0)
arr = np.random.randint(1, 100, 20)
print(arr)
# arr.sort()
# print(arr)
print(np.sort(arr))
print(np.argsort(arr))
print(arr)

[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
[10 13 22 37 40 45 47 48 59 65 66 68 68 71 84 88 88 89 89 89]
[ 5 13  7  8 16  0 18  1 14  2 15  3  4 10  6  9 17 11 12 19]
[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]


In [88]:
print(np.unique(arr))

[10 13 22 37 40 45 47 48 59 65 66 68 71 84 88 89]


In [91]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2)
print(np.concatenate((arr1, arr2)))

[5 7 9]
[1 2 3 4 5 6]


In [94]:
print(np.split(arr, 5))
print(np.split(arr, [6, 12, 18]))

[array([45, 48, 65, 68], dtype=int32), array([68, 10, 84, 22], dtype=int32), array([37, 88, 71, 89], dtype=int32), array([89, 13, 59, 66], dtype=int32), array([40, 88, 47, 89], dtype=int32)]
[array([45, 48, 65, 68, 68, 10], dtype=int32), array([84, 22, 37, 88, 71, 89], dtype=int32), array([89, 13, 59, 66, 40, 88], dtype=int32), array([47, 89], dtype=int32)]


In [95]:
print(np.reshape(arr, [4, 5]))

[[45 48 65 68 68]
 [10 84 22 37 88]
 [71 89 89 13 59]
 [66 40 88 47 89]]
